services:
  budkin:
    build:
      context: .
      dockerfile: Dockerfile.web
    image: git.karellievens.dev/karel/budkin:${TAG:?TAG is required}
    container_name: budkin_web
    ports:
      - "1235:80"
    restart: unless-stopped
