/**
 * Android app shortcuts: long-press the Budkin launcher icon to get Feed,
 * Diaper and Sleep, each opening the Quick-Log sheet already on the right
 * activity.
 *
 * This is plumbing on top of something that already ships. `budkin://log/<type>`
 * is a live route (`src/app/log/[type].tsx`, resolver `src/lib/logDeepLink.ts`)
 * that the Status widget's buttons and the treatment reminders already use. A
 * shortcut fires the same intent, so it opens the form and writes nothing, and
 * a tap before onboarding lands on `/onboarding` rather than dead-ending
 * (`[type].tsx` redirects when `connected` is false).
 *
 * It has to be a config plugin because `android/` is gitignored and fully
 * regenerated by `expo prebuild`, so a hand-written `res/xml/shortcuts.xml`
 * would be deleted the first time anyone prebuilt. Three things have to land
 * together for Android to see a static shortcut:
 *
 *   1. `res/xml/shortcuts.xml`, listing them.
 *   2. `<meta-data android:name="android.app.shortcuts">` pointing at it, on the
 *      activity holding the MAIN/LAUNCHER intent filter. On `<application>` it
 *      is silently ignored.
 *   3. A `@string` resource per label. `android:shortcutShortLabel` rejects a
 *      literal at build time, it must be a resource reference.
 *
 * CommonJS rather than TypeScript for the reason given in
 * `plugins/quickLogShortcuts.js`: prebuild's loader strips types but then
 * resolves relative imports as `.js`.
 */

const fs = require('node:fs');
const path = require('node:path');

const { AndroidConfig, withAndroidManifest, withDangerousMod, withStringsXml } = require('expo/config-plugins');

const { GLYPH_COLOR, GLYPH_SCALE, PLATE_PATH, QUICK_LOG_SHORTCUTS, shortcutDeepLink } = require('./quickLogShortcuts');

/** The `android:name` every launcher shortcut manifest entry hangs off. */
const SHORTCUTS_META_DATA = 'android.app.shortcuts';

/** Generated files say so, since `android/` looks hand-editable but is not. */
const GENERATED_BY = 'plugins/withQuickLogShortcuts.js';

/**
 * The activity a shortcut's intent names explicitly.
 *
 * Explicit rather than implicit: an implicit ACTION_VIEW on `budkin://` would
 * be resolved by the system, and with the development variant installed
 * alongside the release app there are two apps in the running for a very
 * similar scheme. Naming the component removes the question.
 *
 * Both halves are derived, never hardcoded. `APP_VARIANT=development` rewrites
 * `android.package` (see app.config.js), so a literal would point the dev
 * build's shortcuts at the release app.
 *
 * @param {string} androidPackage
 * @returns {string}
 */
function mainActivityClass(androidPackage) {
  return `${androidPackage}.MainActivity`;
}

/**
 * Resolve a manifest `android:name` to a fully qualified class, the way aapt
 * does: a leading dot, or a bare name with no dots at all, is relative to the
 * application id.
 *
 * @param {string} name
 * @param {string} androidPackage
 * @returns {string}
 */
function qualifyActivityName(name, androidPackage) {
  if (name.startsWith('.')) return `${androidPackage}${name}`;
  if (!name.includes('.')) return `${androidPackage}.${name}`;
  return name;
}

/**
 * Read the scheme the app actually registers. `expo.scheme` may be a single
 * string or a list; the first entry is the primary one, and it is the one the
 * generated intent-filter treats as canonical.
 *
 * @param {import('expo/config-plugins').ExpoConfig} config
 * @returns {string}
 */
function primaryScheme(config) {
  const scheme = Array.isArray(config.scheme) ? config.scheme[0] : config.scheme;
  if (!scheme) {
    throw new Error(`${GENERATED_BY}: expo.scheme is not set, so there is no deep link for a launcher shortcut to fire.`);
  }
  return scheme;
}

/**
 * @param {import('expo/config-plugins').ExpoConfig} config
 * @returns {string}
 */
function androidPackage(config) {
  const pkg = config.android?.package;
  if (!pkg) {
    throw new Error(`${GENERATED_BY}: expo.android.package is not set, so a shortcut intent cannot name a target.`);
  }
  return pkg;
}

/**
 * A VectorDrawable: the activity's colour as a filled disc, with the glyph
 * scaled down inside it. See `quickLogShortcuts.js` for why it is a plate
 * rather than a bare glyph.
 *
 * A vector, not a set of PNGs, because these three glyphs are already plain
 * fill-only paths in a 24x24 box, and Android's `pathData` takes SVG path
 * syntax as is. That avoids adding binary assets and rasterising them per
 * density for something that is one colour and a few curves.
 *
 * @param {import('./quickLogShortcuts').QuickLogShortcut} shortcut
 * @returns {string}
 */
function vectorDrawableXml(shortcut) {
  const glyphPaths = shortcut.glyph.map((d) => `    <path\n        android:fillColor="${GLYPH_COLOR}"\n        android:pathData="${d}" />`).join('\n');
  return `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by ${GENERATED_BY}. Edits are lost on the next prebuild. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="48dp"
    android:height="48dp"
    android:viewportWidth="24"
    android:viewportHeight="24">
  <path
      android:fillColor="${shortcut.plateColor}"
      android:pathData="${PLATE_PATH}" />
  <group
      android:pivotX="12"
      android:pivotY="12"
      android:scaleX="${GLYPH_SCALE}"
      android:scaleY="${GLYPH_SCALE}">
${glyphPaths}
  </group>
</vector>
`;
}

/**
 * @param {string} scheme
 * @param {string} pkg
 * @returns {string}
 */
function shortcutsXml(scheme, pkg) {
  const entries = QUICK_LOG_SHORTCUTS.map(
    (shortcut) => `  <shortcut
      android:shortcutId="${shortcut.id}"
      android:enabled="true"
      android:icon="@drawable/${shortcut.resourceName}"
      android:shortcutShortLabel="@string/${shortcut.resourceName}_short_label"
      android:shortcutLongLabel="@string/${shortcut.resourceName}_long_label">
    <intent
        android:action="android.intent.action.VIEW"
        android:targetPackage="${pkg}"
        android:targetClass="${mainActivityClass(pkg)}"
        android:data="${shortcutDeepLink(scheme, shortcut)}" />
  </shortcut>`
  ).join('\n');

  // Document order is Feed, Diaper, Sleep, which is the rank Android assigns
  // and the same order the widget uses. Where they land visually is the
  // launcher's business: the shortcut popup grows away from the icon, so the
  // list reads bottom-up when the icon sits low on the screen. Nothing in this
  // file can change that.
  return `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by ${GENERATED_BY}. Edits are lost on the next prebuild. -->
<shortcuts xmlns:android="http://schemas.android.com/apk/res/android">
${entries}
</shortcuts>
`;
}

/**
 * Writes `res/xml/shortcuts.xml` and the three drawables.
 *
 * A dangerous mod because neither file has a typed mod of its own. Dangerous
 * mods all run before the regular ones, which is fine here: nothing below reads
 * anything a later mod writes.
 *
 * @type {import('expo/config-plugins').ConfigPlugin}
 */
const withShortcutResources = (config) =>
  withDangerousMod(config, [
    'android',
    async (modConfig) => {
      // Introspection asks what the config would produce without touching disk.
      if (modConfig.modRequest.introspect) return modConfig;

      const scheme = primaryScheme(modConfig);
      const pkg = androidPackage(modConfig);
      const res = path.join(modConfig.modRequest.platformProjectRoot, 'app', 'src', 'main', 'res');

      await fs.promises.mkdir(path.join(res, 'xml'), { recursive: true });
      await fs.promises.writeFile(path.join(res, 'xml', 'shortcuts.xml'), shortcutsXml(scheme, pkg), 'utf8');

      await fs.promises.mkdir(path.join(res, 'drawable'), { recursive: true });
      for (const shortcut of QUICK_LOG_SHORTCUTS) {
        await fs.promises.writeFile(path.join(res, 'drawable', `${shortcut.resourceName}.xml`), vectorDrawableXml(shortcut), 'utf8');
      }

      return modConfig;
    },
  ]);

/**
 * The six label strings. `android:shortcutShortLabel` will not take a literal,
 * so these are not optional politeness, the build fails without them.
 *
 * @type {import('expo/config-plugins').ConfigPlugin}
 */
const withShortcutStrings = (config) =>
  withStringsXml(config, (modConfig) => {
    for (const shortcut of QUICK_LOG_SHORTCUTS) {
      modConfig.modResults = AndroidConfig.Strings.setStringItem(
        [
          AndroidConfig.Resources.buildResourceItem({ name: `${shortcut.resourceName}_short_label`, value: shortcut.shortLabel }),
          AndroidConfig.Resources.buildResourceItem({ name: `${shortcut.resourceName}_long_label`, value: shortcut.longLabel }),
        ],
        modConfig.modResults
      );
    }
    return modConfig;
  });

/**
 * Points the launcher activity at `res/xml/shortcuts.xml`.
 *
 * The activity is found by its MAIN/LAUNCHER intent filter rather than by name,
 * because that filter is what makes an activity the one Android offers
 * shortcuts for. `getRunnableActivity` does exactly that lookup.
 *
 * @type {import('expo/config-plugins').ConfigPlugin}
 */
const withShortcutsMetaData = (config) =>
  withAndroidManifest(config, (modConfig) => {
    const pkg = androidPackage(modConfig);
    const activity = AndroidConfig.Manifest.getRunnableActivity(modConfig.modResults);
    if (!activity) {
      throw new Error(`${GENERATED_BY}: no activity in AndroidManifest.xml has a MAIN/LAUNCHER intent filter, so there is nothing to hang launcher shortcuts off.`);
    }

    // The intents in shortcuts.xml name their target activity explicitly, and
    // they are written by a dangerous mod that runs before this one, so it has
    // to assume the class rather than read it. Fail loudly here if the
    // assumption stops holding, e.g. if a future Expo template renames
    // MainActivity: a wrong class name would otherwise ship as three shortcuts
    // that do nothing when tapped.
    const launcherClass = qualifyActivityName(activity.$['android:name'], pkg);
    if (launcherClass !== mainActivityClass(pkg)) {
      throw new Error(
        `${GENERATED_BY}: expected the launcher activity to be ${mainActivityClass(pkg)}, found ${launcherClass}. ` +
          'Update mainActivityClass() so the generated shortcut intents point at the right component.'
      );
    }

    // Re-runnable: `expo prebuild` without --clean replays mods over files that
    // may already carry this.
    activity['meta-data'] = (activity['meta-data'] ?? []).filter((item) => item.$['android:name'] !== SHORTCUTS_META_DATA);
    activity['meta-data'].push({ $: { 'android:name': SHORTCUTS_META_DATA, 'android:resource': '@xml/shortcuts' } });

    return modConfig;
  });

/** @type {import('expo/config-plugins').ConfigPlugin} */
const withQuickLogShortcuts = (config) => withShortcutsMetaData(withShortcutStrings(withShortcutResources(config)));

module.exports = withQuickLogShortcuts;
